/**
 * NEXOS Frontend Hydration & Catalog Service
 * Production React hydration layer for b2b.handsandhead.com
 * 
 * Performance & Cost Architecture:
 * 1. CDN Firestore Bundle Cold-Start: Loads pre-baked binary bundle from Cloud Storage CDN
 *    saving per-user Firestore reads across 15,000 concurrent buyers.
 * 2. Scoped Cursor Pagination: Zero collection-wide onSnapshot listeners. Uses strict
 *    limit(N) + startAfter(cursor) live queries.
 * 3. Stale-While-Revalidate Caching: In-memory & local cache layer with 5-minute TTL.
 * 4. Typesense / Algolia Search Adapter: Offloads full-text and faceted filtering from Firestore.
 */

import {
  collection,
  query,
  where,
  orderBy,
  limit,
  startAfter,
  getDocs,
  doc,
  getDoc,
  loadBundle,
  namedQuery,
  QueryDocumentSnapshot,
  DocumentData,
  Firestore,
} from 'firebase/firestore';

export interface WholesaleTier {
  tierNumber: 1 | 2 | 3;
  minQuantity: number;
  discountPercentage: number;
  unitPriceUsd: number;
  totalTierCostUsd: number;
}

export interface ProvenanceBadge {
  badgeId: string;
  badgeLabel: string;
  certificationAuthority: string;
  originRegion: string;
  traceabilityGrade: 'A_PLUS_ARTISANAL' | 'EXPORT_GRADE_CLASS_A' | 'FACTORY_DIRECT';
  materialCompliance: string[];
  ecoScore: number;
}

export interface FederatedProduct {
  id: string;
  sku: string;
  title: string;
  handle: string;
  description: string;
  category: string;
  origin: 'shop.handsandhead.com' | 'arutemika.com';
  originDisplayName: string;
  status: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | 'OUT_OF_STOCK';
  retailPriceUsd: number;
  currency: 'USD';
  moq: number;
  wholesalePriceLadder: [WholesaleTier, WholesaleTier, WholesaleTier];
  provenance: ProvenanceBadge;
  images: string[];
  thumbnailUrl: string;
  materials: string[];
  tags: string[];
  specifications: Record<string, string | number | boolean>;
  inventoryCount: number;
  inStock: boolean;
  leadTimeDays: number;
  hsCode?: string;
  syncVersion: number;
  redirectUrlPath: string; // e.g. /api/redirect/:id (protects raw D2C URL)
  createdAt: string;
  updatedAt: string;
  lastSyncedAt: string;
  featuredScore: number;
}

export interface CatalogQueryParams {
  category?: string;
  origin?: 'shop.handsandhead.com' | 'arutemika.com' | 'ALL';
  pageSize?: number;
  lastDocCursor?: QueryDocumentSnapshot<DocumentData> | null;
}

export interface PaginatedResult<T> {
  items: T[];
  nextCursor: QueryDocumentSnapshot<DocumentData> | null;
  hasMore: boolean;
  totalLoaded: number;
  source: 'CDN_BUNDLE' | 'FIRESTORE_LIVE' | 'CACHE';
}

// In-Memory Stale-While-Revalidate Cache
interface CacheEntry<T> {
  data: T;
  cachedAt: number;
  ttlMs: number;
}

const memoryCache = new Map<string, CacheEntry<any>>();
const DEFAULT_TTL_MS = 5 * 60 * 1000; // 5 minutes

function getCached<T>(key: string): { hit: boolean; isStale: boolean; data?: T } {
  const entry = memoryCache.get(key);
  if (!entry) return { hit: false, isStale: false };
  const age = Date.now() - entry.cachedAt;
  return {
    hit: true,
    isStale: age > entry.ttlMs,
    data: entry.data as T,
  };
}

function setCache<T>(key: string, data: T, ttlMs = DEFAULT_TTL_MS): void {
  memoryCache.set(key, {
    data,
    cachedAt: Date.now(),
    ttlMs,
  });
}

/**
 * 1. Cold-Start CDN Bundle Hydration
 * Fetches the binary Firestore bundle generated by Cloud Functions and writes it
 * into the local Firestore IndexedDB/memory cache.
 */
export async function hydrateFromCdnBundle(
  db: Firestore,
  bundleUrl = '/bundles/latest-catalog.bundle'
): Promise<FederatedProduct[]> {
  const cacheKey = `cdn_bundle_${bundleUrl}`;
  const cached = getCached<FederatedProduct[]>(cacheKey);
  if (cached.hit && !cached.isStale && cached.data) {
    return cached.data;
  }

  try {
    const response = await fetch(bundleUrl, {
      headers: { Accept: 'application/octet-stream' },
    });

    if (!response.ok) {
      throw new Error(`Bundle fetch returned HTTP ${response.status}`);
    }

    const bundleBuffer = await response.arrayBuffer();
    await loadBundle(db, bundleBuffer);

    // Retrieve cached documents from the named query baked into the bundle
    const namedQ = await namedQuery(db, 'top-active-catalog');
    if (!namedQ) {
      throw new Error('Named query "top-active-catalog" not found in bundle');
    }

    const snap = await getDocs(namedQ);
    const items: FederatedProduct[] = snap.docs.map((d) => d.data() as FederatedProduct);

    setCache(cacheKey, items, 10 * 60 * 1000); // 10 minutes TTL
    return items;
  } catch (bundleErr) {
    console.warn('[Hydration] CDN bundle load skipped or failed. Falling back to live queries.', bundleErr);
    return [];
  }
}

/**
 * 2. Scoped Cursor-Paginated Live Query
 * Enforces limit(N) and startAfter(cursor).
 * ZERO unbounded onSnapshot listeners.
 */
export async function fetchPaginatedCatalog(
  db: Firestore,
  params: CatalogQueryParams = {}
): Promise<PaginatedResult<FederatedProduct>> {
  const { category, origin, pageSize = 12, lastDocCursor = null } = params;

  const cacheKey = `catalog_${category || 'all'}_${origin || 'all'}_${pageSize}_${lastDocCursor?.id || 'root'}`;
  const cached = getCached<PaginatedResult<FederatedProduct>>(cacheKey);

  if (cached.hit && !cached.isStale && cached.data) {
    return { ...cached.data, source: 'CACHE' };
  }

  try {
    const catalogColl = collection(db, 'federated_catalog');
    let q = query(
      catalogColl,
      where('status', '==', 'ACTIVE'),
      orderBy('featuredScore', 'desc')
    );

    if (category && category !== 'ALL') {
      q = query(q, where('category', '==', category));
    }

    if (origin && origin !== 'ALL') {
      q = query(q, where('origin', '==', origin));
    }

    if (lastDocCursor) {
      q = query(q, startAfter(lastDocCursor), limit(pageSize));
    } else {
      q = query(q, limit(pageSize));
    }

    const snap = await getDocs(q);
    const items = snap.docs.map((docSnap) => ({
      ...docSnap.data(),
      id: docSnap.id,
    })) as FederatedProduct[];

    const nextCursor = snap.docs.length >= pageSize ? snap.docs[snap.docs.length - 1] : null;

    const result: PaginatedResult<FederatedProduct> = {
      items,
      nextCursor,
      hasMore: snap.docs.length >= pageSize,
      totalLoaded: items.length,
      source: 'FIRESTORE_LIVE',
    };

    setCache(cacheKey, result);
    return result;
  } catch (err) {
    console.error('[NEXOS Catalog] Failed to fetch paginated catalog:', err);
    throw err;
  }
}

/**
 * 3. Single Product Lookup by Composite ID
 */
export async function fetchFederatedProductById(
  db: Firestore,
  catalogId: string
): Promise<FederatedProduct | null> {
  const cacheKey = `product_${catalogId}`;
  const cached = getCached<FederatedProduct>(cacheKey);
  if (cached.hit && !cached.isStale && cached.data) {
    return cached.data;
  }

  const docRef = doc(db, 'federated_catalog', catalogId);
  const snap = await getDoc(docRef);

  if (!snap.exists()) return null;

  const product = { ...snap.data(), id: snap.id } as FederatedProduct;
  setCache(cacheKey, product, 15 * 60 * 1000);
  return product;
}

/**
 * 4. Typesense / Algolia Search Adapter
 * Production recommended approach for full-text search, facet filtering,
 * and high-frequency keystroke queries instead of costly Firestore inequality queries.
 */
export interface SearchFacetFilter {
  category?: string[];
  origin?: ('shop.handsandhead.com' | 'arutemika.com')[];
  minEcoScore?: number;
  maxPrice?: number;
}

export interface SearchOptions {
  query: string;
  page?: number;
  hitsPerPage?: number;
  filters?: SearchFacetFilter;
}

export interface SearchResult {
  hits: FederatedProduct[];
  totalHits: number;
  page: number;
  totalPages: number;
  facetCounts: {
    categories: Record<string, number>;
    origins: Record<string, number>;
  };
  processingTimeMs: number;
}

/**
 * Typesense / Algolia Wire-Up
 * In production: talks to https://search.handsandhead.com or Algolia index `federated_catalog`.
 * Includes graceful client-side fallback matching if search cluster is offline.
 */
export async function searchFederatedCatalog(
  options: SearchOptions,
  catalogFallback: FederatedProduct[] = []
): Promise<SearchResult> {
  const searchEndpoint = process.env.TYPESENSE_SEARCH_ENDPOINT || process.env.VITE_SEARCH_ENDPOINT;
  const searchApiKey = process.env.TYPESENSE_SEARCH_KEY || process.env.VITE_SEARCH_API_KEY;

  if (searchEndpoint && searchApiKey) {
    try {
      const response = await fetch(`${searchEndpoint}/collections/federated_catalog/documents/search`, {
        method: 'POST',
        headers: {
          'X-TYPESENSE-API-KEY': searchApiKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          q: options.query || '*',
          query_by: 'title,description,materials,tags,category,sku',
          facet_by: 'category,origin',
          page: options.page || 1,
          per_page: options.hitsPerPage || 20,
          filter_by: buildTypesenseFilter(options.filters),
        }),
      });

      if (response.ok) {
        const json = await response.json();
        return {
          hits: json.hits.map((h: any) => h.document as FederatedProduct),
          totalHits: json.found || 0,
          page: json.page || 1,
          totalPages: Math.ceil((json.found || 0) / (options.hitsPerPage || 20)),
          facetCounts: parseTypesenseFacets(json.facet_counts),
          processingTimeMs: json.search_time_ms || 1,
        };
      }
    } catch (searchErr) {
      console.warn('[Search] Typesense cluster unavailable. Using in-memory fallback search.', searchErr);
    }
  }

  // Graceful in-memory search fallback across hydrated catalog
  const startTime = performance.now();
  const q = options.query.toLowerCase().trim();

  let filtered = catalogFallback.filter((p) => {
    if (q) {
      const matchText = `${p.title} ${p.description} ${p.sku} ${p.category} ${p.materials.join(' ')} ${p.tags.join(' ')}`.toLowerCase();
      if (!matchText.includes(q)) return false;
    }
    if (options.filters?.origin?.length && !options.filters.origin.includes(p.origin)) {
      return false;
    }
    if (options.filters?.category?.length && !options.filters.category.includes(p.category)) {
      return false;
    }
    if (options.filters?.minEcoScore && p.provenance.ecoScore < options.filters.minEcoScore) {
      return false;
    }
    if (options.filters?.maxPrice && p.retailPriceUsd > options.filters.maxPrice) {
      return false;
    }
    return true;
  });

  const page = options.page || 1;
  const perPage = options.hitsPerPage || 20;
  const totalHits = filtered.length;
  const totalPages = Math.ceil(totalHits / perPage);
  const pagedHits = filtered.slice((page - 1) * perPage, page * perPage);

  // Derive facet counts
  const categories: Record<string, number> = {};
  const origins: Record<string, number> = {};

  catalogFallback.forEach((item) => {
    categories[item.category] = (categories[item.category] || 0) + 1;
    origins[item.origin] = (origins[item.origin] || 0) + 1;
  });

  return {
    hits: pagedHits,
    totalHits,
    page,
    totalPages,
    facetCounts: { categories, origins },
    processingTimeMs: Math.round(performance.now() - startTime),
  };
}

function buildTypesenseFilter(filters?: SearchFacetFilter): string {
  if (!filters) return '';
  const parts: string[] = [];
  if (filters.category?.length) {
    parts.push(`category:[${filters.category.join(',')}]`);
  }
  if (filters.origin?.length) {
    parts.push(`origin:[${filters.origin.join(',')}]`);
  }
  if (filters.minEcoScore) {
    parts.push(`ecoScore:>=${filters.minEcoScore}`);
  }
  if (filters.maxPrice) {
    parts.push(`retailPriceUsd:<=${filters.maxPrice}`);
  }
  return parts.join(' && ');
}

function parseTypesenseFacets(rawFacets: any[] = []): {
  categories: Record<string, number>;
  origins: Record<string, number>;
} {
  const categories: Record<string, number> = {};
  const origins: Record<string, number> = {};

  if (!Array.isArray(rawFacets)) return { categories, origins };

  for (const facet of rawFacets) {
    if (facet.field_name === 'category' && Array.isArray(facet.counts)) {
      for (const c of facet.counts) {
        categories[c.value] = c.count;
      }
    }
    if (facet.field_name === 'origin' && Array.isArray(facet.counts)) {
      for (const c of facet.counts) {
        origins[c.value] = c.count;
      }
    }
  }

  return { categories, origins };
}
